[package]
name = "OTP"
version = "0.0.1"

[dependencies]
AptosFramework = { git = 'https://github.com/aptos-labs/aptos-core.git', subdir = 'aptos-move/framework/aptos-framework', rev = '6f83bc6d02207298b2dee91133d75538789bf582' }
AptosTokenObjects = { git = 'https://github.com/aptos-labs/aptos-core.git', subdir = 'aptos-move/framework/aptos-token-objects', rev = '6f83bc6d02207298b2dee91133d75538789bf582' }
Pyth = { git = "https://github.com/pyth-network/pyth-crosschain.git", subdir = "target_chains/aptos/contracts", rev = "main" }

# [dev-dependencies]

[addresses]
otp = "b666ec88e97c82f1ec5612c3447fd9ba6fbe394572e115bacb9c3d3b091e171c"
admin_address = "b666ec88e97c82f1ec5612c3447fd9ba6fbe394572e115bacb9c3d3b091e171c"
# On deployment, these should be overridden with --named-addresses using the addresses
# documented at https://docs.pyth.network/documentation/pythnet-price-feeds/aptos#addresses
pyth = "_"
deployer = "_"
wormhole = "_"

[dev-addresses]
pyth = "0x377f0d7c4aaeea8dd73a7a2c6bc817e59aea569e1f9ae0d2f4a80ea1be93bf01"
deployer = "0x277fa055b6a73c42c0662d5236c65c864ccbf2d4abd21f174a30c8b786eab84b"
wormhole = "0x251011524cd0f76881f16e7c2d822f0c1c9510bfd2430ba24e1b3d52796df204"